name: Publish snapshots to maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
      - '[0-9]+.x'

jobs:
  build-and-publish-snapshots:
    strategy:
      fail-fast: false
      matrix:
        jdk: [21]
        platform: ["ubuntu-latest"]
    if: github.repository == 'opensearch-project/alerting'
    runs-on: ${{ matrix.platform }}

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: ${{ matrix.jdk }}
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1
        with:
          role-to-assume: ${{ secrets.PUBLISH_SNAPSHOTS_ROLE }}
          aws-region: us-east-1
      - name: publish snapshots to maven
        run: |
          export SONATYPE_USERNAME=$(aws secretsmanager get-secret-value --secret-id maven-snapshots-username --query SecretString --output text)
          export SONATYPE_PASSWORD=$(aws secretsmanager get-secret-value --secret-id maven-snapshots-password --query SecretString --output text)
          echo "::add-mask::$SONATYPE_USERNAME"
          echo "::add-mask::$SONATYPE_PASSWORD"
          ./gradlew publishShadowPublicationToSnapshotsRepository
          ./gradlew publishPluginZipPublicationToSnapshotsRepository
